'use strict';

goog.provide('Blockly.CodlyCustom');

Blockly.CodlyCustom = function() {

};

Blockly.CodlyCustom.CSS = [
  '@import url(https://fonts.googleapis.com/earlyaccess/notosanskr.css);',  
  /**
   * Overwrite blockly's css
   */
  '.blocklyWidgetDiv {',
    'border-radius : 10px;',
  '}',  
  '.blocklyTooltipDiv {',
    'font-family: "Noto Sans CJK KR", sans-serif;',  
  '}',  
  '.blocklyHighlightedConnectionPath {',
    'stroke: #3ed37a;',
    'stroke-width: 3px;',
  '}',
  '.blocklyPathLight {',
    'fill: #333333;',
    'stroke-width: 2;',
    'opacity : 0.2;',
    'stroke:#333333;',
  '}',

  '.canStartBlock>.blocklyPath {',
    'stroke: #ec6b6b;',
    'stroke-width: 3px;',
    'transform: translateZ(0);',
  '}',

  '.blocklySelected>.blocklyPath {',
    'stroke: #3ed37a;',
    'stroke-width: 3px;',
  '}',
  
  '.blocklySelectedHint>.blocklyPath {',
    'stroke: #3ed37a;',
    'stroke-width: 3px;',
  '}',
  '.blocklyText {',
    'font-size: 12px;',
    'font-family: "Noto Sans CJK KR", sans-serif;',
  '}',
  '.blocklyNonEditableText>rect,',
  '.blocklyEditableText>rect {',
    'fill: #97d450;',
    'fill-opacity: 0;',   
  '}',

  '.blocklyNonEditableText>text,',
  '.blocklyEditableText>text {',
    'cursor: default;',
    'font-size: 12px;',
    'font-family: "Noto Sans CJK KR", sans-serif;',
    'fill: #fff;',
  '}',
  '.blocklyEditableText:hover>text {',
    'cursor:pointer;',
    'fill : black;',
    'font-weight: normal;',
  '}',
  '.blocklyEditableTextNoneBlock>rect {',
    'fill: #fff;',
    'fill-opacity: .6;',
    
  '}',
  '.blocklyEditableTextNoneBlock>text {',
    'fill: #000;', 
    'cursor: default;',
    'font-size: 12px;',
    'font-family: "Noto Sans CJK KR", sans-serif;',
  '}',

  '.blocklyEditableTextNoneBlock:hover>rect {',
    'stroke: #fff;',
    'stroke-width: 2;',
  '}',

  '.blocklyEditableTextNoneBlock:hover>text {',
    'cursor:pointer;',
    'fill : black;',
    'font-weight: normal;',
    'stroke-width: 2;',
  '}',
  '.blocklyHtmlInput {',    
    'font-family: "Noto Sans CJK KR", sans-serif;',
    'text-align: center;',
    'background-color: #97d450;',
    'color:black;',
  '}',
  '.blocklyMainBackground {',
    'stroke-width: 0;',
  '}',
  '.blocklyFlyoutBackground {',
    'fill-opacity: 1;',
  '}',
  '.blocklyTreeRow {',
    'text-align: center;',
    'width: 80px;',
    'height: 30px;',
    'background-position: 50% 2px;',
    'padding-top: 30px;',
    'background-repeat: no-repeat;',
    'background-position-x: 24px;',
    'background-position-y: 2px;',
    'border-bottom: 1px solid #ededed;',
  '}',

  /**
   * For customizing block
   */
  '.eventBlockPath {',
    'fill: #ffa492;',
  '}',
  '.eventBlockPath, .startArrow .inputCondition, .pathDump, .icon_dump, .icon_dump_copy, .icon_background, .messageback{',
    'fill-rule: evenodd;',
  '}',
  '.iconOutlineCricle, .inputTextFontcss, .blockText, .icon_dump, .icon_dump_copy, .icon_background{',
    'fill: #fff;',
  '}',
  '.inputCondition{',
    'fill: #333;',
  '}',
  '.startArrow, .icon_circle_image, .messageback {',
    'fill: #ee6c52;',
  '}',
  '.question_cicle {',
    'fill: #F2A200;',
  '}',
  '.messageback {',
    'opacity: 0.5;',
  '}',
  '.motionBlockPath {',
    'fill: #ffd400;',
  '}',
  '.motionBlockPath, .iconForward {',
    'fill-rule: evenodd;',
  '}',
  '.blockTextBox {',
    'fill: #97d450;',
  '}',
  '.blockText {',
    'font-size: 12px;',
    'text-anchor: middle;',
    'font-family: "Noto Sans KR", sans-serif;',
  '}',
  '.iconForward {',
   'fill: #f2a200;',
  '}',
  '.controlBlockPath {',
    'fill: #3fd1da;',
  '}',

  '.controlBlockPath, .ic_replay_css, .ic_loop-2_css {',
    'fill-rule: evenodd',
  '}',

  '.inputbox_css {',
    'fill: #97d450;',
  '}',
  '.variable_css {',
    'fill: #5CA6FF;',
  '}',
  '.string_css {',
    'fill: #0099FF;',
  '}',
  '.inputTextFontcss, .dummyStatementFontCss, .icon_if_text {',
    'font-size: 12px;',
    'font-family: "Noto Sans CJK KR", sans-serif;',
    'font-weight : bold;',
  '}',
  '.inputTextFontcss {',
    'text-anchor: middle;',
  '}',

  '.dummyStatementFontCss, .ic_replay_css {',
    'opacity: 0.6;',
    'fill: #333;',
  '}',
  '.icon_dump_copy {',
    'opacity: 0.6;',
  '}',
  '.icon_circle_image {',
    'opacity: 0.4;',
  '}',
  '.ic_loop-2_css {',
    'fill: #1b8e95;',
  '}',
  '.icon_if_text {',
    'fill: #1b8e95;',
    'font-weight: 700;',
  '}',
  '.pathDump, .block_boolean, .block_number {',
    'fill: #97d450;',
  '}',
  '.icon_filter {',
    'filter: url(#blendFilter);',
  '}',
  '.icon_filter_red {',
    'filter: url(#blendFilter_red);',
  '}',
  '#grepp_category {',
    'width: 74px;',
    'height: 100%;',
    'display: block;',
    'float: left',
  '}',
  '#grepp_code{',
    'width:100%;',
    'float:left;',
    'height: 100%;',
  '}',
  '#grepp_palette{',
    'width:20%;',
    'float:left;',
    'height:100%;',
  '}',
  '#categoryUl {',
    'padding: 0;',
  '}',
  '.category_lists {',
    'list-style-type: none;',
    'clear : both;',
    'border-bottom : 1px solid #a6cafb;',
    'width: 64px;',
    'text-align: center;',
    'background-color: #edf5f7;',
    'font-size : 14px;',
    'color : #474747;',
    'float : left;',
    'cursor: pointer;',
    'font-family: "Noto Sans CJK KR", sans-serif;',
    'background-repeat : no-repeat;',
    'height: 61px;',
    'background-position: 50% 6px;',
    'padding-top: 38px;',
  '}',
  '.greppCateSeleted {',
    'background-color: #ededed;', 
  '}',
  '.blocklyButtonCanvas {',
    'z-index: 20000;',
    'fill: gray;',
  '}',
  '.blocklyButtonCanvas:hover {',
    'cursor:pointer;',
  '}',
  '.math_wrapper_css, .logic_boolean_wrapper_css {',
    'fill : #ccbb87;',
  '}',
  '.procedure_css {',
    'fill : #A081E2;',
  '}',
  '.procedure_icon_css {',
    'fill : #7C67B2;',
  '}',
  '.marker_gray {',
    //'fill : #949494;',
    'fill-opacity: .5;',
  '}',
  '.cursor_set_css {',
    'fill : #0E59B5;',
  '}',
  '.abstract_algo {',
    'fill : #FF891D;',
  '}',
  '.cursor_algo_move_first {',
    'fill : #EE5B00;',
  '}',
  '.cursor_algo_move_pos {',
    'fill : #F2A200;',
  '}',
  '.cursor_algo_swap {',
    'fill : #EE5B00;',
  '}',
  '.cursor_blue {',
    'fill : blue !important;',
    'font-weight : bold;',
  '}',
  '.cursor_green {',
    'fill : #0f670f !important;',
    'font-weight : bold;',
  '}',
  '.do_not_use_icon {',
    'fill : #868686;',
  '}',
  '.do_not_use_path {',
    'fill : #D1D1D1;',
  '}',
  ''
];

